### PR TITLE
Added autopin after installation

### PR DESCRIPTION
**Pull request by aachernyakevich-sc**
Linked issue — #1109

### CODE REVIEW

**Comment by aachernyakevich-sc** [comment]
@Drive4ik Hi! Please, check this pull request.

**Comment by achernyakevich-sc** [comment]
@Drive4ik I have seen you was active today on some issue. Could you approve and merge this PR and correspondingly resolve #1109. :)

**Comment by achernyakevich-sc** [comment]
@Drive4ik 

I have seen you just was active on #291. Could you approve and merge this PR and correspondingly resolve #1109.

**Comment by Drive4ik** [comment]
I'm sorry I've been out of touch for so long. Yes and now not much time, but I will try to support the addon, and maybe soon I will make a release.

**Comment by achernyakevich-sc** [comment]
@Drive4ik I know that it is uneasy. I support you.

**Pull request merged**
