### PR TITLE
Update Swedish translations

### PR DESCRIPTION
**Pull request by slovdahl**

### CODE REVIEW

**Comment by Drive4ik** [comment]
Done. Thanks for help!

**Comment by slovdahl** [comment]
Just curious, why don't you merge the pull request and preserve the commit history?

**Comment by Drive4ik** [comment]
I re-check all translations in the translation tool in order not to do all this manually. So convenient)
But I also indicate in the commits the names of those who did the translation and wrote their name in the "Enter your name" field

**Comment by slovdahl** [comment]
I appreciate it! :) But it would still be technically possible to retain the original commit as well.

**Comment by Drive4ik** [comment]
I also thought so at the beginning, but then I realized that not everyone has an account on github or a desire to create one, and this may prevent the desire to help with the translation))
Therefore, I decided to do everything through the mail - everyone has it :)

**Pull request closed without merging**
